version: '3.8'
services:
  php:
    build: .
    ports:
      - "80:80"
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=my-secret-pw"
    volumes:
      - db:/data/db
volumes:
  db: